WIP: Add Private Write
Signed-off-by: Michal Czyz <mczyz@antmicro.com>

add controller documentation stub chapter

Enable HCI queues testing

[RTL] clear hwclr field in hci

[RTL] remove DISABLE_LOOPBACK configuration in i3c_defines.svh

[CI] update CI to include hc tests

[CI] add host controller tests on main branch

[Doc] Add controller active docs

[#90281] Bump verilator

[#90635] Pin cocotb version

[RTL] Add todos in flow_active

[DV] add immmediate write block level test

Internal-tag: [#90013]

[DV] add testplan configuration files for planned top level tests

Internal-tag: [#90013]

[DV] add VIP for flow active block tests

Internal-tag: [#90013]

[DV] send 2 cmd descriptors in flow active block level test

Internal-tag: [#90013]

[CI] add hc tests in CI

Internal-tag: [#90013]

[RTL] implement i3c_controller_fsm

[DV] add top level controller VIP

Internal-tag: [#90013]

[RTL] add CSR for T_DS_OD (Figure 144 basic Spec)

Internal-tag: [#90013]

[DV] test private write on top level

Internal-tag: [#90013]

[DV] add controller write target read test

Internal-tag: [#90013]

[CI] add 8GB of RAM for controller tests

Internal-tag: [#90013]

[RTL] add descriptions for controller modules

Internal-tag: [#90013]

[GIT] remove local files from remote

Internal-tag: [#90013]

[RTL] parametrize width of timing signals

Internal-tag: [#90013]

[DV] add fixme comments to testplan

Internal-tag: [#90013]

[DV] enable testplanner

Signed-off-by: Michal Czyz <mczyz@antmicro.com>

[RTL] implement regular transfer descriptor

Internal-tag: [#91257]

[DV] implement tests for regular transfer descriptor

Internal-tag: [#91257]

[CI] add short test for regular transfer descriptor

Internal-tag: [#91257]

diff --git a/.ci.yml b/.ci.yml
--- a/.ci.yml
+++ b/.ci.yml
@@ -1,3 +1,350 @@
-include:
-  - project: chipsalliance-ci-scripts
-    file: i3c-core.yaml
+stages:
+  - prebuild
+  - build
+  - build-docs
+  - deploy
+
+variables:
+  TEST_COVERAGE_ENABLE: 1
+  # Set to 1 when testing changes in build_docs coverage postprocessing to
+  # make sure it won't fail with SKIP_CUSTOM or SKIP_VERILATOR options.
+  TEST_SKIP_OPTIONS: 0
+  SKIP_CUSTOM: 0
+  SKIP_VERILATOR: 0
+
+.build_docs_templ:
+  stage: build-docs
+  variables:
+    GIT_SUBMODULE_STRATEGY: normal
+  image: debian:bookworm
+  before_get_sources:
+    - apt-get update &>/dev/null
+    - apt-get install python3-venv python3-pip python3 git nodejs npm -y &>/dev/null
+  before_script:
+    - export I3C_ROOT_DIR="`pwd`"
+    - python3 -m venv .venv/
+    - source .venv/bin/activate
+    - pip3 install -r requirements.txt
+    - pip3 install -r doc/requirements.txt
+  script:
+    - |
+      set -ex
+      source .venv/bin/activate
+      
+      # Docs can't be built if there are no XML files which can happen with only some jobs enabled
+      if [ "$(find artifacts -name '*.xml')" != "" ]; then
+        env REPO_URL="https://dev.antmicro.com/git/repositories/i3c-host-mode-i3c-core/blob/main" TESTS_RESULTS_DIR=./artifacts make verification-docs-with-sim
+        cd doc/
+        make html
+        cd ../
+      fi
+    - tar cf $CI_DOCS_ARCHIVE -C doc/build/html/ .
+    - mv doc/build .
+
+build_docs:
+  extends: .build_docs_templ
+  artifacts:
+    paths:
+      - build
+      - $CI_DOCS_ARCHIVE
+    when: always
+
+# This job, after setting TEST_SKIP_OPTIONS to 1, will test `build_docs` with
+# artifacts from one Verilator job to make sure it won't fail with SKIP_CUSTOM.
+test_build_docs_with_skip_custom_single:
+  extends: .build_docs_templ
+  dependencies: [verilator_cocotb_axi_single]
+  only:
+    variables:
+      - $TEST_SKIP_OPTIONS == "1"
+  except:
+    refs:
+      - main
+    variables:
+      - $SKIP_VERILATOR == "1"
+
+test_build_docs_with_skip_custom_main:
+  extends: .build_docs_templ
+  dependencies: [verilator_cocotb_axi_main]
+  only:
+    refs:
+      - main
+    variables:
+      - $TEST_SKIP_OPTIONS == "1"
+  except:
+    variables:
+      - $SKIP_VERILATOR == "1"
+
+deploy:
+  image: $CI_DOCS_DOCKER_IMAGE
+  dependencies: [build_docs]
+  stage: deploy
+  tags: [docs]
+  variables:
+    GIT_STRATEGY: none
+  script: echo 'Deploying docs'
+  artifacts:
+    paths:
+      - $CI_DOCS_ARCHIVE
+
+verilator_build:
+  image: debian:bookworm
+  stage: prebuild
+  except:
+    variables:
+      - $SKIP_VERILATOR == "1"
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: none
+    SCALENODE_CPU: 8
+    SCALENODE_RAM: 8192
+    SCALENODE_DISK: 8
+  before_get_sources:
+    - apt -qqy update 2> /dev/null > /dev/null
+    - apt -qqy --no-install-recommends install wget curl help2man libfl-dev make g++ git bison flex gperf libreadline-dev libbz2-dev autoconf python3-dev python3-venv python3-jsonschema python3-yaml python3-sphinx python3-docopt 2> /dev/null > /dev/null
+  script:
+    - git clone --branch v5.044 https://github.com/verilator/verilator
+    - cd verilator
+    - autoconf 2> /dev/null > /dev/null
+    - ./configure 2> /dev/null > /dev/null
+    - make -j$(nproc) 2> /dev/null > /dev/null
+    - rm -rf .git*
+    - cd ..
+  artifacts:
+    paths:
+      - verilator
+
+icarus_build:
+  image: debian:bookworm
+  stage: prebuild
+  except:
+    variables:
+      - $SKIP_VERILATOR == "1"
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: none
+    SCALENODE_CPU: 8
+    SCALENODE_RAM: 8192
+    SCALENODE_DISK: 8
+  before_get_sources:
+    - apt -qqy update 2> /dev/null > /dev/null
+    - apt -qqy --no-install-recommends install wget curl help2man libfl-dev make g++ git bison flex gperf libreadline-dev libbz2-dev autoconf python3-dev python3-venv python3-jsonschema python3-yaml python3-sphinx python3-docopt 2> /dev/null > /dev/null
+  script:
+    - git clone https://github.com/steveicarus/iverilog.git
+    - cd iverilog
+    - git checkout 06077ed026b4d8498d9129a6acfb0b44d0b51f18
+    - sh autoconf.sh 2> /dev/null > /dev/null
+    - ./configure 2> /dev/null > /dev/null
+    - make -j$(nproc) 2> /dev/null > /dev/null
+    - rm -rf .git*
+    - cd ..
+  artifacts:
+    paths:
+      - iverilog
+
+generate_vp_docs:
+  image: debian:bookworm
+  stage: prebuild
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_RAM: 4098
+    SCALENODE_DISK: 8
+  before_get_sources:
+    - apt -qqy update &> /dev/null
+    - apt -qqy --no-install-recommends install wget curl help2man libfl-dev make g++ git bison flex gperf libreadline-dev libbz2-dev autoconf python3-dev python3-venv python3-jsonschema python3-yaml python3-sphinx python3-docopt &> /dev/null
+  script:
+    - export I3C_ROOT_DIR="`pwd`"
+    - python3.11 -m venv .venv
+    - source .venv/bin/activate
+    - python3.11 -m pip install -r requirements.txt
+    - make verification-docs
+  artifacts:
+    paths:
+      - verification/testplan/generated
+
+.cocotb_verilator_templ:
+  image: debian:bookworm
+  stage: build
+  dependencies: [verilator_build, icarus_build]
+  except:
+    variables:
+      - $SKIP_VERILATOR == "1"
+  before_get_sources:
+    - apt -qqy update &> /dev/null
+    - apt -qqy --no-install-recommends install wget curl help2man libfl-dev make g++ git bison flex gperf libreadline-dev libbz2-dev autoconf python3-dev python3-venv python3-jsonschema python3-yaml python3-sphinx python3-docopt &> /dev/null
+  before_script:
+    - cd iverilog
+    - make install 2> /dev/null > /dev/null
+    - cd ..
+    - rm -rf iverilog
+    - cd verilator
+    - make install 2> /dev/null > /dev/null
+    - cd ..
+    - rm -rf verilator
+  script:
+    - iverilog -V | head -1
+    - verilator --version
+    - make install-uvm
+    - export I3C_ROOT_DIR="`pwd`"
+    - export CALIPTRA_ROOT="${I3C_ROOT_DIR}/third_party/caliptra-rtl"
+    - python3.11 -m venv .venv
+    - source .venv/bin/activate
+    - python3.11 -m pip install -r requirements.txt
+    - python3.11 -m pip install git+https://github.com/antmicro/info-process.git
+    - make -j1 ${MAKE_TARGET} 2>&1
+  after_script:
+    - mkdir -p artifacts/results-$CI_NODE_INDEX
+    - |
+      if [ "$TEST_COVERAGE_ENABLE" = 1 ]; then
+        source .venv/bin/activate
+
+        COVERAGE_DIR="$(TMP="${CI_JOB_NAME////_}"; echo "artifacts/coverage/${TMP// /_}")"
+        mkdir -p "${COVERAGE_DIR}"
+        COVERAGE_DIR="$(realpath "${COVERAGE_DIR}")"
+        (cd verification/cocotb && find -name \*.dat -not -name Vtop\*.dat | xargs cp -Lrv --parents -t "${COVERAGE_DIR}")
+
+        for cov in $(find "${COVERAGE_DIR}" -type f -name \*.dat); do
+          out_file="$(dirname "${cov}")/$(basename "${cov}" .dat)_verilator.info"
+          verilator_coverage --filter-type "^(?!toggle).*" --write-info "${out_file}" "${cov}"
+          verilator_coverage --filter-type toggle --write-info "${out_file%%_all_verilator.info}_toggle_verilator.info" "${cov}"
+          rm "${cov}"
+
+          info-process extract --coverage-type line --output "${out_file%%_all_verilator.info}_line_verilator.info" "${out_file}"
+          info-process extract --coverage-type cond --output "${out_file%%_all_verilator.info}_cond_verilator.info" "${out_file}"
+          info-process extract --coverage-type branch --output "${out_file%%_all_verilator.info}_branch_verilator.info" "${out_file}"
+          rm "${out_file}"
+        done
+      fi
+    - tar -c `find verification/cocotb -name \*.xml -o -name \*.log -o -name \*.info -o -name \*.vcd -o -name \*.dat -not -name Vtop*.dat` -f logs.tar
+    - cd artifacts/results-$CI_NODE_INDEX
+    - tar xf ../../logs.tar
+  artifacts:
+    paths:
+      - artifacts
+      - verification/cocotb
+    when: always
+
+# verilator_ prefix is stripped for Coverview test names, see build_docs job.
+verilator_cocotb_axi_single:
+  extends: .cocotb_verilator_templ
+  parallel: 1
+  except:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi"
+
+verilator_cocotb_axi_hc_single:
+  extends: .cocotb_verilator_templ
+  parallel: 1
+  except:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi-hc"
+
+verilator_cocotb_axi_controller_single:
+  extends: .cocotb_verilator_templ
+  parallel: 1
+  except:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_RAM: 8192
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi-controller-short"
+
+verilator_cocotb_axi_controller_long:
+  extends: .cocotb_verilator_templ
+  parallel: 1
+  only:
+    - schedules
+  except:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_RAM: 32768
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi-controller"
+
+verilator_cocotb_axi_main:
+  extends: .cocotb_verilator_templ
+  parallel: 10
+  only:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi"
+    
+verilator_cocotb_axi_hc_main:
+  extends: .cocotb_verilator_templ
+  parallel: 10
+  only:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi-hc"
+    
+verilator_cocotb_axi_controller_main:
+  extends: .cocotb_verilator_templ
+  parallel: 10
+  only:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_RAM: 8192
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi-controller-short"
+
+verilator_cocotb_axi_controller_long_main:
+  extends: .cocotb_verilator_templ
+  parallel: 10
+  only:
+    - schedules
+  only:
+    refs:
+      - main
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_RAM: 32768
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-axi-controller"
+
+verilator_cocotb_i2c:
+  extends: .cocotb_verilator_templ
+  parallel: 1
+  variables:
+    DEBIAN_FRONTEND: noninteractive
+    GIT_SUBMODULE_STRATEGY: normal
+    SCALENODE_CPU: 2
+    SCALENODE_DISK: 20
+    MAKE_TARGET: "tests-i2c"
